language:  python
services:
  - docker

python:
  - "2.7"

install:
  - make deps

script:
  - make test

after_success:
  - make docker_build

deploy:
  provider: heroku
  app:  stormy-falls-87126
  api_key: ${HEROKU_API_KEY}
